### PR TITLE
DE9938 Hide "Skip This Version" button

### PR DESCRIPTION
**Pull request by rusminsusanto**
It looks like Sparkle doesn't implement this functionality properly. Considering
time limitation, it's better to just hide this button.

### CODE REVIEW

**Comment by rusminsusanto** [comment]
Sparkle doesn't properly implement "skip this version".
Considering time limitation (and QA resource to test this scenario), Vince has agreed to just hide the button.
So, we should get this in quickly before he changes his mind :smile:

**Comment by rusminsusanto** [comment]
I plan to get this in and then let Jinny test in on master

**Comment by DarrenFordQSR** [comment]
👍

**Comment by HarryWangQSR** [comment]
👍

**Comment by HarryWangQSR** [comment]
👍 👍

**Pull request merged**
