### PR TITLE
Europa

### PR DESCRIPTION
**Pull request by teki**
- merge Sparkel 1.14
- fix build issue

Test: did a successful full update.
No change is required in Europa (apart from the module update).

### CODE REVIEW

**Comment by teki** [comment]
@DarrenFordQSR 
@rusminsusanto 
@lurkerbot

**Comment by teki** [comment]
Ok, I was wrong, it does require some changes in Europa (build/delta generation related).

**Comment by rusminsusanto** [comment]
👍

**Comment by DarrenFordQSR** [comment]
👍

**Comment by labrooks** [comment]
👍 👍

**Pull request merged**
