### PR TITLE
Set the SDK to macosx10.9

### PR DESCRIPTION
**Pull request by teki**
@lurkerbot

### CODE REVIEW

**Comment by peitschie** [comment]
Is this to try and get the europa build to work?

**Comment by peitschie** [comment]
The problem with [http://qsrger/#/c/7650](http://qsrger/#/c/7650) is that it's not referencing the right commit. The latest commit in the europa branch for sparkle is 727e3c86eec96487f6f356daa3404da8a025b690 (see https://github.com/QSRINT/Sparkle/commits/europa), not 8d239aea8b8dab3c36e17336488cc2a712463c3e as you've got tagged in the gerrit patch :smile:

**Comment by teki** [comment]
> Is this to try and get the europa build to work?

For some reason sub projects don't inherit the SDK from the parent project and it defaults to 10.10 with Xcode 6.4

**Comment by teki** [comment]
> The problem with http://qsrger/#/c/7650 is that it's not referencing the right commit.

Updated. Still trying to get the hang of the web of commit & review dependencies :)

**Comment by peitschie** [comment]
> For some reason sub projects don't inherit the SDK from the parent project and it defaults to 10.10 with Xcode 6.4

Yep... I got that as the reason for the change to the europa branch... unsure why you're proposing to re-merge it back into master though as NVivo drives off the europa branch?

**Comment by peitschie** [comment]
> Updated. Still trying to get the hang of the web of commit & review dependencies :)

No worries :grin: 

Git submodules are not the world's easiest concept to learn :disappointed:

**Comment by teki** [comment]
> Yep... I got that as the reason for the change to the europa branch... unsure why you're proposing to re-merge it back into master though as NVivo drives off the europa branch?

Ohh, this was meant to be on a branch, not sure how did I manage to push it :(.

**Comment by teki** [comment]
I can then discard this PR and leave the branch as it is if you are happy with the change.

**Comment by peitschie** [comment]
> I can then discard this PR and leave the branch as it is if you are happy with the change.

Yep... that sounds good to me!

**Comment by teki** [comment]
Ta!

**Pull request closed without merging**
